### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by sweta-singh28**
Updated the favicon with a new and improved version.
issue no. #285 

WhatsApp Image 2024-08-05 at 23 17 50_5861f5d9

### CODE REVIEW

**Comment by sweta-singh28** [comment]
@Sayak-Bhunia sir

**Comment by sweta-singh28** [comment]
@Sayak-Bhunia sir, Could you please merge this PR or provide any update on this? Tomorrow is the last day for GSSoC contributions.

**Comment by sweta-singh28** [comment]
@Sayak-Bhunia sir.

**Comment by abhay-sen** [comment]
@Sayak-Bhunia sirrrrr!

**Pull request closed without merging**
