### PR TITLE
Admin Page

### PR DESCRIPTION
**Pull request by mohdjami**
Created admin page. 
Created roles for each user.
To be an admin user just change the role in the database.
The admin button is hidden on navbar you have to type it expilcitly to view Admin page and all the confessions.

### CODE REVIEW

**Comment by Sayak-Bhunia** [comment]
how can i access the admin panel please provide a video demonstration.

**Comment by mohdjami** [comment]
@Sayak-Bhunia, okay I will do that.

**Comment by Sayak-Bhunia** [comment]
hey i forgot to discuss about this feature.
just give me a demo and i will merge it.
@mohdjami

**Comment by mohdjami** [comment]
Hey @Sayak-Bhunia @Kritika30032002 , Kindly label this PR under gssoc and level3 because I have not recieved any points of this PR.

**Pull request merged**
