### PR TITLE
added workflow for closing old issues

### LINKED ISSUE #145: Feat: Workflow for Closing Old Issues
### Describe the feature

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Add ScreenShots

Close Old Iss

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #145 

@Sayak-Bhunia please review and merge this PR

### CODE REVIEW

**Comment by Asymtode712** [comment]
@Sayak-Bhunia please add the 'gssoc' and 'level' labels to this PR

**Comment by Asymtode712** [comment]
@Sayak-Bhunia I know you are instructed to remove the 'level3' tags but you can assign me 'level1' label for this contribution atleast

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia I know you are instructed to remove the 'level3' tags but you can assign me 'level1' label for this contribution atleast

No they said also not to conside level1.

**Comment by Sayak-Bhunia** [comment]
> > @Sayak-Bhunia I know you are instructed to remove the 'level3' tags but you can assign me 'level1' label for this contribution atleast
> 
> No they said also not to consider level1.

**Comment by Asymtode712** [comment]
@Sayak-Bhunia ok understood

**Pull request merged**
