### PR TITLE
`JWT` auth implemented

### PR DESCRIPTION
**Pull request by psidh**
`Users can`
- sign in
- sign out
- sign up
- using `username` and `password`
- hashed passwords exist on database
- routes are protected 
    > /confess
    > /search
- Token expires in 1 day
- middleware.js also added

### CODE REVIEW

**Comment by psidh** [comment]
Solves #43

**Comment by Sayak-Bhunia** [comment]
The landing page is not showing at all even after sign in it is not redirecting too the previous landing page do fix it ASAP.

**Comment by psidh** [comment]
I have solved the issue sir on my end

# Preview Sir | From where I made PR in #87 
https://github.com/Sayak-Bhunia/mystory/assets/116720762/8e3fd23c-844a-4a30-b649-b1c07a9f7f52

the vercel deployment is having the problem sir
and also once please check out the PR which added the FAQs, because that is causing the issue in production

Screenshot 2024-05-14 at 18 41 16

Below is the problem due to FAQ's PR
Screenshot 2024-05-14 at 18 40 10

**Comment by Kritika30032002** [comment]
@Sayak-Bhunia Is this valid pr?

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia Is this valid pr?

No.

**Pull request merged**
