### PR TITLE
Added About Page 

### LINKED ISSUE #107: [Feature] : Add About Page
### Issue
I want to create an "About" page to provide visitors with information about the site, mission, goals and other relevant details.

### Proposed design: 
image

### Expected Outcome
The "About" page should provide a comprehensive overview of the site, its mission, and the team, enhancing the visitor's understanding and trust. also adding skeleton page into is this can make it look more interactive

kindly assign me this issue under GSSoC '24

### PR DESCRIPTION
**Pull request by ayushnandi**
Resolves #107 
your About section is added

### CODE REVIEW

**Comment by Kritika30032002** [comment]
share the screenshot @ayushnandi

**Comment by ayushnandi** [comment]
> share the screenshot @ayushnandi

image

**Comment by Kritika30032002** [comment]
@ayushnandi  about page is not visible 
look into this and submit anther pr resolving this issue

**Comment by ayushnandi** [comment]
> @ayushnandi about page is not visible look into this and submit anther pr resolving this issue

Hey @Kritika30032002 !

image

I can see my code in your working repository, and it is working perfectly fine in my terminal. Please brief me more about your problem so I can help you with your end.

**Comment by Kritika30032002** [comment]
@ayushnandi  check live website url

**Pull request merged**
