### PR TITLE
[Feature] : Implement Dark & light Mode

### PR DESCRIPTION
**Pull request by sivaprasath2004**
#112 
- The New feature will be added please check and merge it.... :rocket: 

[Screencast from 2024-05-20 22-10-09.webm](https://github.com/Sayak-Bhunia/mystory/assets/121082414/58373efc-2682-45a9-9dbf-0f6a246d9b13)

### CODE REVIEW

**Comment by Sayak-Bhunia** [comment]
> #112 
> - The New feature will be added please check and merge it.... :rocket: 
> 
> 
> [Screencast from 2024-05-20 22-10-09.webm](https://github.com/Sayak-Bhunia/mystory/assets/121082414/58373efc-2682-45a9-9dbf-0f6a246d9b13)
> 

Idk what is wrong but when I am merging it with my branch the color of the footer stays different from the rest of the webpage and also the tracing beam from acernity ui changes color to green when toggled dark mode so please fix that u can check the vercel preview deployment.

**Comment by sivaprasath2004** [comment]
@Sayak-Bhunia `Team Access required`  please screenshot to notify me.... What can I change

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia `Team Access required`  please screenshot to notify me.... What can I change
> 

https://mystory-git-fork-sivaprasath2004-s-84569c-sayakbhunias-projects.vercel.app/?vercelToolbarCode=my3wunN0vin53Ca 
Check this link and ask for access.

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia `Team Access required`  please screenshot to notify me.... What can I change
> 

Gave access now check it out ur self the navbar the footer the tracing beam and other stuff both on smaller and larger screens.

**Comment by sivaprasath2004** [comment]
What can change this

**Comment by sivaprasath2004** [comment]
@Sayak-Bhunia  

Screenshot from 2024-05-21 13-48-43


Screenshot from 2024-05-21 13-47-57

**Pull request closed without merging**
