### PR TITLE
Feat: Added Contributors Page

### LINKED ISSUE #209: Feat: Create a Contributors page
### Describe the feature

- This is an entirely open-source project so we create a contributor page 
- This page will show that we respect our contributors & give them proper credit.
- 1. Creator (here will come your profile) 
-  2. Meet our Contributors (here comes the developer who is contributing to the mystory)

### Add ScreenShots

just reference image
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Vaibhavsg17**
closes #209

### CODE REVIEW

**Comment by Sayak-Bhunia** [comment]
can you provide a video where have u put the contributors section ?

**Comment by Vaibhavsg17** [comment]
[screen-capture.webm](https://github.com/Sayak-Bhunia/mystory/assets/66477893/a3930c51-8d82-486e-8341-96c667389c50)

@Sayak-Bhunia created new page as Contributors

**Comment by Vaibhavsg17** [comment]
[screen-capture (2).webm](https://github.com/Sayak-Bhunia/mystory/assets/66477893/ea2b3a29-8223-4cba-bab1-63de1bc80361)

@Sayak-Bhunia created a new page for contributors

**Comment by Vaibhavsg17** [comment]
@Sayak-Bhunia i have one doubt regarding this pr to merge it right ? then why it not showing contributors page on live webstie

**Pull request merged**
