### PR TITLE
added workflow for closing old PRs

### LINKED ISSUE #146: Feat: Workflow for closing Old PRs
### Describe the feature

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

### Add ScreenShots

Close Old PRs

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #146 

@Sayak-Bhunia please review and merge this PR.

Also, please add the gssoc and level labels

### CODE REVIEW

**Comment by Asymtode712** [comment]
@Sayak-Bhunia please add the 'gssoc' and 'level' labels to this PR

**Comment by Asymtode712** [comment]
@Sayak-Bhunia please add the 'gssoc' and 'level' labels to this PR and all my other merged PRs

Thank you!🙏

**Review by Sayak-Bhunia — COMMENTED** [review]
LGTM

**Comment by Asymtode712** [comment]
@Sayak-Bhunia I know you are instructed to remove the 'level3' tags but you can assign me 'level1' label for this contribution atleast

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia I know you are instructed to remove the 'level3' tags but you can assign me 'level1' label for this contribution atleast

Don't spam bro.

**Comment by Asymtode712** [comment]
@Sayak-Bhunia ok

**Pull request merged**
