### PR TITLE
Solves issue #234

### PR DESCRIPTION
**Pull request by Praneeth-2602**
solves issue #234

### CODE REVIEW

**Comment by Kritika30032002** [comment]
share video of changes @Praneeth-2602

**Comment by Praneeth-2602** [comment]
https://github.com/Sayak-Bhunia/mystory/assets/137754636/ca0bea77-d213-4309-a58a-e6ed5b91ad42

@Kritika30032002 Please review it. I cloned the repo twice but the background won't change to black no matter what!

**Comment by Kritika30032002** [comment]
@Sayak-Bhunia review and merge

**Comment by Kritika30032002** [comment]
@Praneeth-2602 remove the conflicts

**Pull request closed without merging**
