### PR TITLE
Added a scroll neon light effect on both the sides

### PR DESCRIPTION
**Pull request by Vaibhavsg17**
Added a scroll neon light effect on both the sides

https://github.com/Sayak-Bhunia/mystory/assets/66477893/fb0666c7-0848-4ff1-bf67-7e0a55927756

### CODE REVIEW

**Comment by psidh** [comment]
@Vaibhavsg17 
Once pull the latest changes from the `main` branch
because `box` background is added to it, and some other `latest changes` are not being reflected in your PR

**Comment by Kritika30032002** [comment]
@Sayak-Bhunia issue number?

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia issue number?

#25

**Comment by Vaibhavsg17** [comment]
@Kritika30032002  please add the level tag this

**Pull request merged**
