### PR TITLE
#66 #88 Fixed Profile

### PR DESCRIPTION
**Pull request by mohdjami**
#66  Added Profile View For the user
#136 Added Admin route also.
#88 Closed

@Sayak-Bhunia , @Kritika30032002 Label and merge the PR
https://github.com/Sayak-Bhunia/mystory/assets/114595881/bd64da8d-73ec-464e-927d-64e59cda7dc1

### CODE REVIEW

**Comment by Sayak-Bhunia** [comment]
bro can u give me a video demo on how to use the admin ?

**Comment by Sayak-Bhunia** [comment]
i am not able to use the admin and the user profile section.

**Comment by mohdjami** [comment]
@Sayak-Bhunia , Firstly you need to be logged in to view your profile.

Secondly for admin permissions you need to go to the database that is connected and change the role from user to admin of your account explicitly. That's the main goal of admin page that anyone can't change the roles. Ask someone who has the access of database to so that.

**Comment by Sayak-Bhunia** [comment]
@psidh

**Pull request merged**
