### PR TITLE
added read option

### PR DESCRIPTION
**Pull request by Parimalasri13**
i removed about from the navbar i thought of placing it in home page and added all necessary UI for read option

### CODE REVIEW

**Comment by Sayak-Bhunia** [comment]
> i removed about from the navbar i thought of placing it in home page and added all necessary UI for read option 

But why have I assigned any issue like that to u ?

**Comment by Parimalasri13** [comment]
@Sayak-Bhunia not actually but when I placed read option they are getting congested in the navbar  so  changed it where read contains the memes ,lifestories and 3 more sessions loke that

**Comment by Parimalasri13** [comment]
@Sayak-Bhunia sorry i forgot i intimate you before i will change and make other pr can you please then where should i place this new read option

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia sorry i forgot to intimate you before doing, i will change and make other pr again  can you please tellme  where should i place this new read option

Well I don't want the read option to be used.

**Pull request closed without merging**
