### PR TITLE
feature: added contact in footer

### PR DESCRIPTION
**Pull request by Ayesha-Siddiqua88**
I have added a contact option in the footer of the website. This feature includes a mail icon that, when clicked, opens Gmail with the email address, sbhunia2903@gmail.com. This enhancement simplifies the process for users to reach out directly via email.

### CODE REVIEW

**Comment by Sayak-Bhunia** [comment]
ur branch has merge conflicts.

**Comment by Ayesha-Siddiqua88** [comment]
@Sayak-Bhunia I've resolved the conflicts.

**Comment by Kritika30032002** [comment]
@Ayesha-Siddiqua88  Twitter of @Sayak-Bhunia has to be added instead of gssoc. And if you are unable to find his twitter id link then you can add Twitter(https://twitter.com/ ) link

Kindly update this so that i can merge this pr

**Comment by Ayesha-Siddiqua88** [comment]
@Kritika30032002 okay will do it

**Comment by Ayesha-Siddiqua88** [comment]
@Kritika30032002 I've added the twitter link instead of gssoc.

**Review by Kritika30032002 — APPROVED** [review]

**Pull request merged**
